packages: []

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

overrides:
  hono: 4.12.25
  nanoid: ^3.3.18
  postcss: ^8.5.23
  sharp: ^0.35.3

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver
