import type { Locale } from '@/lib/i18n/config'

export const billingCopy = {
  az: {
    title: 'Vestra Pro',
    subtitle:
      'Qarderobunuzu, AI stilisti və hava uyğun planlamanı daha geniş limitlərlə istifadə edin.',
    pageTitle: 'Abunəlik və plan',
    pageSubtitle:
      'Planınızı, billing əməliyyatlarını və Vestra Pro girişinizi idarə edin.',
    free: 'Free',
    freePlanTitle: 'Vestra Free',
    proPlanTitle: 'Vestra Pro',
    proMonthly: 'Pro aylıq',
    proAnnual: 'Pro illik',
    monthly: 'Aylıq',
    annual: 'İllik',
    monthlyPrice: '€4.99/ay',
    annualPrice: '€39.99/il',
    annualSavings: 'Aylıq plana nisbətən təxminən 33% qənaət',
    upgrade: 'Pro-ya keç',
    upgradeAgain: 'Yenidən Pro-ya keç',
    viewPricing: 'Qiymətlərə bax',
    manage: 'Billing-i idarə et',
    cancel: 'Abunəliyi ləğv et',
    resume: 'Abunəliyi bərpa et',
    switchToMonthly: 'Aylıq plana keç',
    switchToAnnual: 'İllik plana keç',
    updatePaymentMethod: 'Ödəniş üsulunu yenilə',
    signIn: 'Daxil olun və checkout-a davam edin',
    currentPlan: 'Cari plan',
    currentLimits: 'Cari limitlər',
    planDetails: 'Plan detalları',
    billingActions: 'Billing əməliyyatları',
    subscriptionStatus: 'Abunəlik statusu',
    billingInterval: 'Billing dövrü',
    nextBillingDate: 'Növbəti ödəniş',
    currentPeriodEnd: 'Cari dövrün sonu',
    noBillingDate: 'Billing tarixi hələ yoxdur',
    statusActive: 'Aktiv',
    statusTrialing: 'Sınaq dövrü aktivdir',
    statusPastDue: 'Ödəniş gecikir',
    statusPaused: 'Dayandırılıb',
    statusCanceled: 'Ləğv edilib',
    statusInactive: 'Free plan',
    cancellationScheduled: 'Ləğv etmə planlaşdırılıb',
    accessUntil: 'Pro girişi {date} tarixinədək aktivdir',
    paymentIssue: 'Ödəniş problemi',
    pastDueDescription:
      'Ödənişlə bağlı problem var. Giriş vəziyyətinizi qorumaq üçün billing portalında ödəniş üsulunu yeniləyin.',
    graceUntil: 'Güzəşt müddəti {date} tarixinədək aktivdir',
    previousProEnded: 'Əvvəlki Pro abunəliyi bitib',
    expiredDescription:
      'Hesabınız hazırda Free planındadır. Pro limitlərini bərpa etmək üçün yenidən yüksəldə bilərsiniz.',
    subscriptionPaused: 'Abunəlik dayandırılıb',
    pausedDescription:
      'Pro hüquqları fasilədədir. Billing portalından statusu idarə edə bilərsiniz.',
    sandboxBadge: 'Paddle Sandbox',
    processing: 'Checkout hazırlanır...',
    actionPending:
      'Dəyişiklik Paddle tərəfindən təsdiqləndikdən sonra status yenilənəcək.',
    configuredLater:
      'Paddle sandbox dəyişənləri tamamlandıqdan sonra checkout açılacaq.',
    checkoutFailed: 'Checkout başlatmaq olmadı.',
    portalFailed: 'Billing portalını açmaq olmadı.',
    lifecycleActionFailed: 'Abunəlik əməliyyatını tamamlamaq olmadı.',
    alreadyActive:
      'Pro abunəliyiniz artıq aktivdir. Planı dəyişmək üçün ayrıca keçid əməliyyatından istifadə edin.',
    ends: 'Bitmə tarixi {date}',
    nextBilling: 'Növbəti ödəniş {date}',
    processingWebhook:
      'Ödənişdən sonra Pro statusu təsdiqlənmiş webhook gələndə aktiv olacaq.',
    confirmCancel:
      'Abunəliyi ləğv etmək istəyirsiniz? Pro girişi ödənilmiş müddətin sonuna qədər qalacaq.',
    features: {
      free: ['30 geyim', 'Həftədə 5 stilist sorğusu', '10 saxlanılan kombin'],
      pro: [
        '300 geyim',
        'Yüksək fair-use AI limitləri',
        '2-3 stilist namizədi',
        'Tam hava uyğun planlama',
      ],
    },
  },
  en: {
    title: 'Vestra Pro',
    subtitle:
      'Use your wardrobe, AI stylist, and weather-aware planner with higher production limits.',
    pageTitle: 'Subscription and plan',
    pageSubtitle: 'Manage your plan, billing actions, and Vestra Pro access.',
    free: 'Free',
    freePlanTitle: 'Vestra Free',
    proPlanTitle: 'Vestra Pro',
    proMonthly: 'Pro Monthly',
    proAnnual: 'Pro Annual',
    monthly: 'Monthly',
    annual: 'Annual',
    monthlyPrice: '€4.99/month',
    annualPrice: '€39.99/year',
    annualSavings: 'Save about 33% compared with monthly',
    upgrade: 'Upgrade to Pro',
    upgradeAgain: 'Upgrade again',
    viewPricing: 'View pricing',
    manage: 'Manage billing',
    cancel: 'Cancel subscription',
    resume: 'Resume subscription',
    switchToMonthly: 'Switch to Monthly',
    switchToAnnual: 'Switch to Annual',
    updatePaymentMethod: 'Update payment method',
    signIn: 'Sign in to continue to checkout',
    currentPlan: 'Current plan',
    currentLimits: 'Current limits',
    planDetails: 'Plan details',
    billingActions: 'Billing actions',
    subscriptionStatus: 'Subscription status',
    billingInterval: 'Billing interval',
    nextBillingDate: 'Next billing',
    currentPeriodEnd: 'Current period end',
    noBillingDate: 'No billing date yet',
    statusActive: 'Active',
    statusTrialing: 'Trial active',
    statusPastDue: 'Past due',
    statusPaused: 'Paused',
    statusCanceled: 'Canceled',
    statusInactive: 'Free plan',
    cancellationScheduled: 'Cancellation scheduled',
    accessUntil: 'Pro access remains active until {date}',
    paymentIssue: 'Payment issue',
    pastDueDescription:
      'There is a payment issue. Update your payment method in the billing portal to keep access stable.',
    graceUntil: 'Grace access remains active until {date}',
    previousProEnded: 'Previous Pro subscription ended',
    expiredDescription:
      'Your account is currently on Free. You can upgrade again to restore Pro limits.',
    subscriptionPaused: 'Subscription paused',
    pausedDescription:
      'Pro entitlements are paused. You can manage the status from the billing portal.',
    sandboxBadge: 'Paddle Sandbox',
    processing: 'Preparing checkout...',
    actionPending:
      'Your status updates after Paddle confirms the change by webhook.',
    configuredLater:
      'Checkout will open after Paddle sandbox variables are configured.',
    checkoutFailed: 'Unable to start checkout.',
    portalFailed: 'Unable to open the billing portal.',
    lifecycleActionFailed: 'Unable to complete the subscription action.',
    alreadyActive:
      'Your Pro subscription is already active. Use plan switching instead of opening a new checkout.',
    ends: 'Ends {date}',
    nextBilling: 'Next billing {date}',
    processingWebhook:
      'After payment, Pro activates only after Vestra receives the verified webhook.',
    confirmCancel:
      'Cancel your subscription? Your Pro access remains active until the end of the paid period.',
    features: {
      free: [
        '30 wardrobe items',
        '5 stylist requests per week',
        '10 saved outfits',
      ],
      pro: [
        '300 wardrobe items',
        'High fair-use AI limits',
        '2-3 stylist candidates',
        'Full weather-aware planning',
      ],
    },
  },
  ru: {
    title: 'Vestra Pro',
    subtitle:
      'Используйте гардероб, AI-стилиста и погодный планировщик с расширенными лимитами.',
    pageTitle: 'Подписка и план',
    pageSubtitle: 'Управляйте планом, оплатой и доступом к Vestra Pro.',
    free: 'Free',
    freePlanTitle: 'Vestra Free',
    proPlanTitle: 'Vestra Pro',
    proMonthly: 'Pro на месяц',
    proAnnual: 'Pro на год',
    monthly: 'Месячный',
    annual: 'Годовой',
    monthlyPrice: '€4.99/месяц',
    annualPrice: '€39.99/год',
    annualSavings: 'Экономия около 33% по сравнению с помесячной оплатой',
    upgrade: 'Перейти на Pro',
    upgradeAgain: 'Снова перейти на Pro',
    viewPricing: 'Посмотреть цены',
    manage: 'Управлять оплатой',
    cancel: 'Отменить подписку',
    resume: 'Возобновить подписку',
    switchToMonthly: 'Перейти на месячный план',
    switchToAnnual: 'Перейти на годовой план',
    updatePaymentMethod: 'Обновить способ оплаты',
    signIn: 'Войдите, чтобы перейти к оплате',
    currentPlan: 'Текущий план',
    currentLimits: 'Текущие лимиты',
    planDetails: 'Детали плана',
    billingActions: 'Действия с оплатой',
    subscriptionStatus: 'Статус подписки',
    billingInterval: 'Период оплаты',
    nextBillingDate: 'Следующее списание',
    currentPeriodEnd: 'Конец текущего периода',
    noBillingDate: 'Дата оплаты пока отсутствует',
    statusActive: 'Активна',
    statusTrialing: 'Пробный период активен',
    statusPastDue: 'Есть задолженность',
    statusPaused: 'Приостановлена',
    statusCanceled: 'Отменена',
    statusInactive: 'Free план',
    cancellationScheduled: 'Отмена запланирована',
    accessUntil: 'Доступ Pro активен до {date}',
    paymentIssue: 'Проблема с оплатой',
    pastDueDescription:
      'Есть проблема с оплатой. Обновите способ оплаты в billing-портале, чтобы сохранить доступ.',
    graceUntil: 'Льготный доступ активен до {date}',
    previousProEnded: 'Предыдущая подписка Pro завершилась',
    expiredDescription:
      'Сейчас аккаунт находится на Free. Вы можете снова перейти на Pro, чтобы вернуть расширенные лимиты.',
    subscriptionPaused: 'Подписка приостановлена',
    pausedDescription:
      'Pro-доступ поставлен на паузу. Управлять статусом можно в billing-портале.',
    sandboxBadge: 'Paddle Sandbox',
    processing: 'Готовим checkout...',
    actionPending:
      'Статус обновится после подтверждения изменения через webhook Paddle.',
    configuredLater:
      'Checkout откроется после настройки переменных Paddle sandbox.',
    checkoutFailed: 'Не удалось запустить checkout.',
    portalFailed: 'Не удалось открыть billing portal.',
    lifecycleActionFailed: 'Не удалось выполнить действие с подпиской.',
    alreadyActive:
      'Ваша подписка Pro уже активна. Используйте смену плана вместо новой оплаты.',
    ends: 'Закончится {date}',
    nextBilling: 'Следующее списание {date}',
    processingWebhook:
      'После оплаты Pro активируется только после проверенного webhook в Vestra.',
    confirmCancel:
      'Отменить подписку? Доступ Pro останется активным до конца оплаченного периода.',
    features: {
      free: [
        '30 вещей',
        '5 запросов стилисту в неделю',
        '10 сохранённых образов',
      ],
      pro: [
        '300 вещей',
        'Высокие fair-use лимиты AI',
        '2-3 варианта от стилиста',
        'Полное погодное планирование',
      ],
    },
  },
}

export function getBillingCopy(locale: Locale) {
  return billingCopy[locale]
}
