import type { Locale } from '@/lib/i18n/config'
import type { PlannerOccasion } from './types'

export const plannerOccasions = [
  'everyday',
  'university',
  'work',
  'business',
  'date',
  'dinner',
  'party',
  'sport',
  'travel',
  'outdoor',
  'formal_event',
] as const satisfies PlannerOccasion[]

export const plannerCopy = {
  az: {
    title: 'Hava uyğun kombin planlayıcısı',
    subtitle:
      'Qarderobunuzdakı real geyimlərlə hava, plan və günə uyğun kombin seçin.',
    month: 'Ay',
    selectedDay: 'Seçilmiş gün',
    today: 'Bugün',
    tomorrow: 'Sabah',
    upcoming: 'Növbəti planlar',
    weather: 'Hava',
    weatherUnavailable: 'Hava məlumatı əlçatan deyil',
    weatherChanged: 'Hava dəyişib. Kombini uyğunlaşdırmağı düşünün.',
    plannedOutfit: 'Planlaşdırılmış kombin',
    noPlannedOutfit: 'Bu gün üçün kombin planlaşdırılmayıb.',
    generate: 'Bu gün üçün kombin yarat',
    adapt: 'Kombini uyğunlaşdır',
    chooseSaved: 'Saxlanılan kombin seç',
    useOutfit: 'Bu kombini istifadə et',
    changeOutfit: 'Kombini dəyiş',
    removeFromCalendar: 'Təqvimdən sil',
    moveToDate: 'Başqa günə keçir',
    markWornQuestion: 'Bu kombini geyindiniz?',
    markWorn: 'Bəli, geyindim',
    markSkipped: 'Xeyr',
    location: 'Məkan',
    locationPlaceholder: 'Bakı, Vyana, Klagenfurt',
    useGeolocation: 'Cari məkanı istifadə et',
    saveLocation: 'Məkanı yenilə',
    occasion: 'Plan',
    customNote: 'Qısa qeyd',
    customNotePlaceholder: 'Məsələn: açıq havada axşam',
    candidates: 'Tövsiyə olunan variantlar',
    savedOutfits: 'Saxlanılan kombinlər',
    suitable: 'Havaya uyğundur',
    weak: 'Bu kombin proqnoza tam uyğun olmaya bilər.',
    tooWarm: 'Bu kombin proqnoz üçün çox isti ola bilər.',
    tooLight: 'Bu kombin proqnoz üçün yüngül ola bilər.',
    scheduled: 'Kombin təqvimə əlavə edildi.',
    loading: 'Yüklənir...',
    outfitScheduled: 'Kombin planlaşdırılıb',
    forecast: 'Proqnoz',
    feelsLike: 'Hiss olunur {value}°C',
    highLow: '{min}° / {max}°C',
    precipitation: 'Yağıntı ehtimalı {value}%',
    errors: {
      load: 'Planlayıcını yükləmək olmadı.',
      save: 'Planı saxlamaq olmadı.',
      generate: 'Kombin yaratmaq olmadı.',
      saved: 'Saxlanılan kombinləri yükləmək olmadı.',
      weather_not_configured: 'Hava provayderi konfiqurasiya edilməyib.',
      weather_credentials_missing: 'Hava provayderi konfiqurasiya edilməyib.',
      weather_invalid_location: 'Məkan düzgün deyil.',
      weather_location_not_found: 'Məkan tapılmadı.',
      weather_rate_limited: 'Hava xidməti limiti keçdi.',
      weather_timeout: 'Hava sorğusu vaxtı bitdi.',
      weather_provider_unavailable: 'Hava xidməti müvəqqəti işləmir.',
    },
    occasions: {
      everyday: 'Gündəlik',
      university: 'Universitet',
      work: 'İş',
      business: 'Biznes',
      date: 'Görüş',
      dinner: 'Şam yeməyi',
      party: 'Ziyafət',
      sport: 'İdman',
      travel: 'Səyahət',
      outdoor: 'Açıq hava',
      formal_event: 'Rəsmi tədbir',
    },
  },
  en: {
    title: 'Weather-aware outfit planner',
    subtitle:
      'Plan outfits from your real wardrobe around the weather, occasion, and day.',
    month: 'Month',
    selectedDay: 'Selected day',
    today: 'Today',
    tomorrow: 'Tomorrow',
    upcoming: 'Next scheduled outfits',
    weather: 'Weather',
    weatherUnavailable: 'Weather unavailable',
    weatherChanged: 'Weather changed. Consider adapting this outfit.',
    plannedOutfit: 'Planned outfit',
    noPlannedOutfit: 'No outfit is planned for this day.',
    generate: 'Generate outfit for this day',
    adapt: 'Adapt outfit',
    chooseSaved: 'Choose saved outfit',
    useOutfit: 'Use this outfit',
    changeOutfit: 'Change outfit',
    removeFromCalendar: 'Remove from calendar',
    moveToDate: 'Move to another date',
    markWornQuestion: 'Did you wear this outfit?',
    markWorn: 'Yes, I wore it',
    markSkipped: 'No',
    location: 'Location',
    locationPlaceholder: 'Baku, Vienna, Klagenfurt',
    useGeolocation: 'Use current location',
    saveLocation: 'Update location',
    occasion: 'Occasion',
    customNote: 'Short note',
    customNotePlaceholder: 'Example: outdoor evening',
    candidates: 'Recommended options',
    savedOutfits: 'Saved outfits',
    suitable: 'Suitable for the weather',
    weak: 'This outfit may not fully match the forecast.',
    tooWarm: 'This outfit may be too warm for the forecast.',
    tooLight: 'This outfit may be too light for the forecast.',
    scheduled: 'Outfit added to the calendar.',
    loading: 'Loading...',
    outfitScheduled: 'Outfit scheduled',
    forecast: 'Forecast',
    feelsLike: 'Feels like {value}°C',
    highLow: '{min}° / {max}°C',
    precipitation: 'Precipitation chance {value}%',
    errors: {
      load: 'Unable to load planner.',
      save: 'Unable to save the plan.',
      generate: 'Unable to generate outfits.',
      saved: 'Unable to load saved outfits.',
      weather_not_configured: 'Weather provider is not configured.',
      weather_credentials_missing: 'Weather provider is not configured.',
      weather_invalid_location: 'Location is invalid.',
      weather_location_not_found: 'Location was not found.',
      weather_rate_limited: 'Weather service rate limit reached.',
      weather_timeout: 'Weather request timed out.',
      weather_provider_unavailable:
        'Weather service is temporarily unavailable.',
    },
    occasions: {
      everyday: 'Everyday',
      university: 'University',
      work: 'Work',
      business: 'Business',
      date: 'Date',
      dinner: 'Dinner',
      party: 'Party',
      sport: 'Sport',
      travel: 'Travel',
      outdoor: 'Outdoor',
      formal_event: 'Formal event',
    },
  },
  ru: {
    title: 'Планировщик образов по погоде',
    subtitle:
      'Планируйте образы из своего гардероба с учетом погоды, повода и дня.',
    month: 'Месяц',
    selectedDay: 'Выбранный день',
    today: 'Сегодня',
    tomorrow: 'Завтра',
    upcoming: 'Следующие планы',
    weather: 'Погода',
    weatherUnavailable: 'Погода недоступна',
    weatherChanged: 'Погода изменилась. Стоит адаптировать образ.',
    plannedOutfit: 'Запланированный образ',
    noPlannedOutfit: 'На этот день образ не запланирован.',
    generate: 'Создать образ на этот день',
    adapt: 'Адаптировать образ',
    chooseSaved: 'Выбрать сохраненный образ',
    useOutfit: 'Использовать этот образ',
    changeOutfit: 'Изменить образ',
    removeFromCalendar: 'Удалить из календаря',
    moveToDate: 'Перенести на другую дату',
    markWornQuestion: 'Вы надели этот образ?',
    markWorn: 'Да, надел(а)',
    markSkipped: 'Нет',
    location: 'Локация',
    locationPlaceholder: 'Баку, Вена, Клагенфурт',
    useGeolocation: 'Использовать текущую локацию',
    saveLocation: 'Обновить локацию',
    occasion: 'Повод',
    customNote: 'Короткая заметка',
    customNotePlaceholder: 'Например: вечер на улице',
    candidates: 'Рекомендованные варианты',
    savedOutfits: 'Сохраненные образы',
    suitable: 'Подходит для погоды',
    weak: 'Этот образ может не полностью подходить прогнозу.',
    tooWarm: 'Этот образ может быть слишком теплым для прогноза.',
    tooLight: 'Этот образ может быть слишком легким для прогноза.',
    scheduled: 'Образ добавлен в календарь.',
    loading: 'Загрузка...',
    outfitScheduled: 'Образ запланирован',
    forecast: 'Прогноз',
    feelsLike: 'Ощущается как {value}°C',
    highLow: '{min}° / {max}°C',
    precipitation: 'Вероятность осадков {value}%',
    errors: {
      load: 'Не удалось загрузить планировщик.',
      save: 'Не удалось сохранить план.',
      generate: 'Не удалось создать образ.',
      saved: 'Не удалось загрузить сохраненные образы.',
      weather_not_configured: 'Провайдер погоды не настроен.',
      weather_credentials_missing: 'Провайдер погоды не настроен.',
      weather_invalid_location: 'Локация указана неверно.',
      weather_location_not_found: 'Локация не найдена.',
      weather_rate_limited: 'Лимит сервиса погоды исчерпан.',
      weather_timeout: 'Запрос погоды превысил время.',
      weather_provider_unavailable: 'Сервис погоды временно недоступен.',
    },
    occasions: {
      everyday: 'На каждый день',
      university: 'Университет',
      work: 'Работа',
      business: 'Бизнес',
      date: 'Свидание',
      dinner: 'Ужин',
      party: 'Вечеринка',
      sport: 'Спорт',
      travel: 'Путешествие',
      outdoor: 'На улице',
      formal_event: 'Официальное событие',
    },
  },
} as const

export function getPlannerCopy(locale: Locale) {
  return plannerCopy[locale]
}
